### ISSUE TITLE
invalid Game can be constructed

### ISSUE THREAD

**Issue by flavius** [wolfenste/tictactoe#17]
Think of error conditions and throw exceptions in the constructor if the game which is about to be constructed is not valid. Read your document `rules.md`.

Don't forget to write tests first.

**Comment by wolfenste** [comment]
Yes, I know, I am aware of that. Both players can be X or 0 or even worse (because Player's constructor is faulty too), we can have non_symbol players. Map can be constructed with an array of non object elements. I have a lot to do. :) For me the most difficult part is to find relevant commit messages and test method identifiers. I do not know yet, maybe I should keep a consistent commit message style; by now it is a mess.

**Comment by wolfenste** [comment]
Actually I do know, I read about that, commit messages should follow a consistent style.
